### PR TITLE
Pulling schema when on a new branch

### LINKED ISSUE #26: Pulling schema on `init` fails if the current branch doesn't exists in Xata
When running `xata init` and reusing an exising database, the CLI will try to pull the schema for that database on the current local branch. This will fail if that branch doesn't exists on Xata:

```
Pulling database schema...
Error pulling schema: Error getting branch details: database branch [technical-docs-1645523204403:easier-onboarding] not found
```

We should detect this situation and let the user choose between starting with a fresh schema or pulling from a different branch

### PR DESCRIPTION
**Pull request by tsg**
This improves the workflow around running `xata init` or `xata pull` when on a git branch that doesn't have an associated DB branch. We prompt the user if they want to pull from another branch. This fixes #26.

https://user-images.githubusercontent.com/101817/156733139-077a4225-c048-452e-a07d-707a34051698.mp4

Also adds more E2E testing around `xata pull` and `xata init`.

### CODE REVIEW

File: cmd/auth_e2e_test.go [hunk 1]
```diff
@@ -234,6 +234,7 @@ func loginWithKey(t *testing.T, config *TestConfig, configDir string) {
 }
 
 func TestAuthStatus(t *testing.T) {
+	t.Skip("TestAuth broken")
```
Comment (urso) [inline cmd/auth_e2e_test.go:237]: Please add an issue and link from the comment to the issue.

Comment (tsg) [reply cmd/auth_e2e_test.go]: I've unskipped it here, because this wasn't helping with anything. Instead I've opened https://github.com/xataio/cli/pull/40 to disable E2E tests altogether for now.

File: cmd/init_e2e_test.go [hunk 2]
```diff
@@ -112,6 +114,43 @@ func TestInit(t *testing.T) {
...
+	require.NoError(t, err)
+
+	_, err = c.SendLine(dbName)
+	require.NoError(t, err)
+
+	_, err = c.ExpectString("Init done. Edit xata/schema.json to get started.")
+	require.NoError(t, err)
+
+	err = cmd.Wait()
+	require.NoError(t, err)
```
[the remark this answers is not in the document]
Comment (tsg) [reply cmd/init_e2e_test.go:131]: Thanks, I've added a note to https://github.com/xataio/cli/issues/39 to do this. I suspect to fix that we might need to rework the `startCommand` anyway.

**Review by exekias — APPROVED** [review]
